// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: grade.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createGrade = `-- name: CreateGrade :one
INSERT INTO grades (name,school_id,status) 
VALUES($1,$2,$3) 
RETURNING id, name, school_id, status, created_at, updated_at, deleted_at
`

type CreateGradeParams struct {
	Name     string
	SchoolID uuid.UUID
	Status   Status
}

func (q *Queries) CreateGrade(ctx context.Context, arg CreateGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, createGrade, arg.Name, arg.SchoolID, arg.Status)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchoolID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
