// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: schools.sql

package db

import (
	"context"
	"database/sql"
)

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (name,logo) VALUES ($1,$2)
RETURNING id, name, logo, created_at, updated_at, deleted_at
`

type CreateSchoolParams struct {
	Name string
	Logo sql.NullString
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, createSchool, arg.Name, arg.Logo)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
