// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: student.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (user_id,status)
VALUES ($1,$2) RETURNING id, user_id, status, created_at, updated_at, deleted_at
`

type CreateStudentParams struct {
	UserID uuid.UUID
	Status Status
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.UserID, arg.Status)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
