// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: teachers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTechers = `-- name: CreateTechers :one
INSERT INTO teachers(user_id,title,status) 
VALUES ($1,$2,$3)
RETURNING id, user_id, title, status, created_at, updated_at, deleted_at
`

type CreateTechersParams struct {
	UserID uuid.UUID
	Title  string
	Status NullStatus
}

func (q *Queries) CreateTechers(ctx context.Context, arg CreateTechersParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, createTechers, arg.UserID, arg.Title, arg.Status)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
